#+title: opencv-install-notes

* Installation

The following was completed successfully on Pop!_OS 20.10.

** From source

NOTE: Disable all python virtual envs before proceeding.

NOTE: I'm choosing to install v4.3.0, as this is the newest version supported by opencv-rust.

System prereqs:

#+begin_src sh

sudo apt install build-essential cmake git pkg-config libgtk-3-dev \
    libavcodec-dev libavformat-dev libswscale-dev libv4l-dev \
    libxvidcore-dev libx264-dev libjpeg-dev libpng-dev libtiff-dev \
    gfortran openexr libatlas-base-dev python3-dev python3-numpy \
    libtbb2 libtbb-dev libdc1394-22-dev libopenexr-dev \
    libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev

#+end_src

Create dirs, clone repos. Checking out v4.3.0 for compatability with opencv-rust.

#+begin_src 

mkdir ~/opencv_build
cd ~/opencv_build
git clone https://github.com/opencv/opencv.git
cd opencv
git checkout tags/4.3.0
cd ..
git clone https://github.com/opencv/opencv_contrib.git
cd opencv_contrib
git checkout tags/4.3.0
cd ..

cd ~/opencv_build/opencv
mkdir -p build && cd build

#+end_src

Configure build

#+begin_src sh

cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D INSTALL_C_EXAMPLES=ON \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D OPENCV_GENERATE_PKGCONFIG=ON \
    -D OPENCV_EXTRA_MODULES_PATH=~/opencv_build/opencv_contrib/modules \
    -D BUILD_EXAMPLES=ON ..

#+end_src

Make build and install. Note the number following =j= should be the output of =nproc= command

#+begin_src sh

make -j16

sudo make install

#+end_src

Verify

#+begin_src sh

pkg-config --modversion opencv4

#+end_src

** Rust bindings

Use the following to allow usage of Rust bindings. Again, note that only opencv 4.3.0. is currently supported.

Add the following environmental variables to =variables.bash=

#+begin_src sh

CV_DIR="HOME/opencv_build/opencv"
export OpenCV_DIR="$CV_DIR/cmake"
export LD_LIBRARY_PATH="$CV_DIR/build/lib"
export LLVM_CONFIG_PATH="/usr/bin/llvm-config-11"
export LIBCLANG_PATH="/usr/lib/x86_64-linux-gnu"

#+end_src

Install the additional system dependencies:

#+begin_src sh

sudo apt install ninja-build clang

#+end_src

Put the following in your =Cargo.toml=

#+begin_src rs

opencv = {version = "0.46", default-features = false, features = ["opencv-4", "buildtime-bindgen", "contrib"]}

#+end_src

And try this in =main.rs=

#+begin_src rs

use opencv::prelude::*;

#+end_src

Now run =cargo build=.
